apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: ctse2024/product-service:${{ github.run_id }}
        ports:
        - containerPort: 5003
